//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InserimentoDatiCroceRossa.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarTar()
        {
            this.Ins = new HashSet<Ins>();
        }
    
        public int CarTarOwnId { get; set; }
        public int CarId { get; set; }
        public int TarId { get; set; }
        public bool CarTarEnb { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Tar Tar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ins> Ins { get; set; }
    }
}
