//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InserimentoDatiCroceRossa.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ins
    {
        public int InsOwnId { get; set; }
        public System.DateTime InsSvrDat { get; set; }
        public int InsSvrFrm { get; set; }
        public int InsSvrTo { get; set; }
        public int InsTyp { get; set; }
        public int InsPerId { get; set; }
        public int InsPatId { get; set; }
        public int InsCarTarId { get; set; }
        public Nullable<System.TimeSpan> InsTimIn { get; set; }
        public Nullable<System.TimeSpan> InsTimOut { get; set; }
        public int InsKmOut { get; set; }
        public int InsKmInt { get; set; }
        public int InsAutId { get; set; }
        public int InsSoc1Id { get; set; }
        public int InsSoc2Id { get; set; }
        public int InsChrTo { get; set; }
        public int InsBilNum { get; set; }
        public int InsCrtNum { get; set; }
        public string InsIndVal { get; set; }
        public string InsPlcVal { get; set; }
    
        public virtual CarTar CarTar { get; set; }
        public virtual Ent Ent { get; set; }
        public virtual Vol Vol { get; set; }
        public virtual Pat Pat { get; set; }
        public virtual Per Per { get; set; }
        public virtual Vol Vol1 { get; set; }
        public virtual Vol Vol2 { get; set; }
        public virtual Loc Loc { get; set; }
        public virtual Loc Loc1 { get; set; }
    }
}
