//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InserimentoDatiCroceRossa.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc
    {
        public int LocOwnId { get; set; }
        public string LocPlc { get; set; }
    }
}
