//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InserimentoDatiCroceRossa.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Per
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Per()
        {
            this.Ins = new HashSet<Ins>();
        }
    
        public int PerOwnId { get; set; }
        public string PerFCd { get; set; }
        public string PerNam { get; set; }
        public string PerSur { get; set; }
        public Nullable<bool> PerSex { get; set; }
        public System.DateTime PerBir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ins> Ins { get; set; }
    }
}
