CREATE TABLE [dbo].[Ins] (
    [InsOwnId]    INT      IDENTITY (1, 1) NOT NULL,
    [InsSvrDat]   DATETIME NOT NULL,
    [InsSvrFrm]   INT      NOT NULL,
    [InsSvrTo]    INT      NOT NULL,
    [InsTyp]      INT      NOT NULL,
    [InsPerId]    INT      NOT NULL,
    [InsIndId]    INT      NOT NULL,
    [InsPatId]    INT      NOT NULL,
    [InsCarTarId] INT      NOT NULL,
    [InsTimIn]    TIME (7) NULL,
    [InsTimOut]   TIME (7) NULL,
    [InsKmOut]    INT      NOT NULL,
    [InsKmInt]    INT      NOT NULL,
    [InsAutId]    INT      NOT NULL,
    [InsSoc1Id]   INT      NOT NULL,
    [InsSoc2Id]   INT      NOT NULL,
    [InsChrTo]    INT      NOT NULL,
    [InsBilNum]   INT      NOT NULL,
    [InsCrtNum]   INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([InsOwnId] ASC),
    FOREIGN KEY ([InsAutId]) REFERENCES [dbo].[Vol] ([VolOwnId]),
    FOREIGN KEY ([InsCarTarId]) REFERENCES [dbo].[CarTar] ([CarTarOwnId]),
    FOREIGN KEY ([InsChrTo]) REFERENCES [dbo].[Ent] ([EntOwnId]),
    FOREIGN KEY ([InsIndId]) REFERENCES [dbo].[Ind] ([IndOwnId]),
    FOREIGN KEY ([InsPatId]) REFERENCES [dbo].[Pat] ([PatOwnId]),
    FOREIGN KEY ([InsPerId]) REFERENCES [dbo].[Per] ([PerOwnId]),
    FOREIGN KEY ([InsSoc1Id]) REFERENCES [dbo].[Vol] ([VolOwnId]),
    FOREIGN KEY ([InsSoc2Id]) REFERENCES [dbo].[Vol] ([VolOwnId]),
    FOREIGN KEY ([InsSvrFrm]) REFERENCES [dbo].[Loc] ([LocOwnId]),
    FOREIGN KEY ([InsSvrTo]) REFERENCES [dbo].[Loc] ([LocOwnId])
);

