//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CroceRossaEntities : DbContext
    {
        public CroceRossaEntities()
            : base("name=CroceRossaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarTar> CarTar { get; set; }
        public virtual DbSet<Ent> Ent { get; set; }
        public virtual DbSet<Ind> Ind { get; set; }
        public virtual DbSet<Ins> Ins { get; set; }
        public virtual DbSet<Loc> Loc { get; set; }
        public virtual DbSet<Pat> Pat { get; set; }
        public virtual DbSet<Per> Per { get; set; }
        public virtual DbSet<Tar> Tar { get; set; }
        public virtual DbSet<Vol> Vol { get; set; }
    }
}
